name: smartstruct
description: smartstruct - A dart bean mapper annotation processor - the easy nullsafe way!
version: 1.4.0
homepage: https://github.com/smotastic/smartstruct
environment:
  sdk: '>=3.3.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
dependencies: null
